export const LOGIN_TELEGRAM_REQUEST = "LOGIN_TELEGRAM_REQUEST";
export const LOGIN_TELEGRAM_ERROR = "LOGIN_TELEGRAM_ERROR";
export const LOGIN_TELEGRAM_SUCCESS = "LOGIN_TELEGRAM_SUCCESS";

export const NAV_VISIBLE = "NAV_VISIBLE";
export const NAV_INVISIBLE = "NAV_INVISIBLE";
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const SORT_BY_XP = "SORT_BY_XP";
export const SORT_BY_WINS = "SORT_BY_WINS";

export const BASE_URL = "https://52.233.153.23/api";
